<?php


function galli_theme() {
  return array(
    'galli' => array(
      'render element' => 'elements',
      'template' => 'galli',
    ),
  );
}

function template_preprocess_galli(&$variables) {
  $elements = $variables['elements'];

  $variables['galli']['id'] = $elements['galli']['id'];
  $variables['galli']['name'] = $elements['galli']['name'];
  $variables['galli']['person_name'] = $elements['galli']['person_name'];
  $variables['galli']['person_first_name'] = $elements['galli']['person_first_name'];
  $variables['galli']['person_location'] = $elements['galli']['person_location'];
}